version: '2'

services:
    # db:
    #     image: mysql
    #     volumes:
    #         - "./.data/db:/var/lib/mysql"
    #     environment:
    #         MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    #         MYSQL_DATABASE: ${MYSQL_DATABASE}
    #         MYSQL_USER: ${MYSQL_USER}
    #         MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    rmq:
            image: rabbitmq:3-management
            volumes: 
                - ./rabbitmq:/var/lib/rabbitmq/
                - ./logs/rabbitmq:/var/log/rabbitmq/
            ports:
                - 5672:5672
                - 15672:15672

    php:
        build:
            context: php7-fpm
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/app/logs
    nginx:
        build: nginx
        ports:
            - 80:80
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx
    elk:
        image: elasticsearch
        ports:
            - 9200:9200
        volumes:
            - ./elasticsearch/data/:/usr/share/elasticsearch/data
            - ./elasticsearch/logs/:/usr/share/elasticsearch/logs
    